sudo: false

language: generic

env:
  global:
  - 'PATH=$HOME/.cargo/bin/:$PATH'

matrix:
  include:
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl
  #- os: osx
  #  env: TARGET=x86_64-apple-darwin

addons:
  apt:
    packages:
    - upx-ucl

script:
- make bootstrap all
- cp target/$TARGET/release/ts ts-$TRAVIS_TAG-$TARGET

deploy:
  provider: releases
  api_key:
    secure: j/VTC/ktEiWcXds59uGKYYmYYffToawWCCknkHWEC4TtriOjoPInpnRC6wFLoIA+lcbYnU8c7EsoTwMRwecJtHQsWjmrMke6SAJHOXqD7fuFyDuGEOoDZs8QfJgEAw/zGz7EOwbke4UrGjmrFSu5P9DCRcrljG3JX6gBh4Czz2wSTGsed25iFGjyG6IKAVxxnEoyOAkGPQKVybFJU5rREzmj66KHP7iNQikTv6Y6bHD/LKba6J1P1bwOTWSS93jlUaNd3eVcVGJGtu2J/spbKT8MZfEVo/GfZdz49ni5QsL3yAMmEtUBJk5lGQ/mOGdaobcgUNE3PpgfVI5YZoH4IMCuuZPcgNrkWRw34k1wiAgYCcaPPloX/1+t1VUQSvuJD6ExaPeCwXYrBcivWzHb6DCTF7BA+NcFy/bsLoTmJ0pSggK5ZzU/Om6wU0NhJam0Y82NGhJ30NRicKhJrw7r9ulqysgFRbvFFFrH4mQBP6TSSVeEgQ6FCFBq0j1SsZOvQhWQUT5aeyjQhQqvqL7E7g7LIj0xCq9coBu9jr61U0ke/M5bitjbMP2G/0Noos0HHfK/nmpdqBfVseuuQtpzJvNCMzjDX/HQIpBCy5I0MFsYUMRdG/dA6HQ3dQriuwJt+c5+p18LGX6cNKl4NWWFluKzacrjNRh7FJfAFTMYkwg=
  file: ts-$TRAVIS_TAG-$TARGET
  skip_cleanup: true
  on:
    repo: gdvalle/ts
    tags: true
