sudo: false

language: generic

env:
  global:
  - 'PATH=$HOME/.cargo/bin/:$PATH'

matrix:
  include:
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl
  #- os: osx
  #  env: TARGET=x86_64-apple-darwin

addons:
  apt:
    packages:
    - upx-ucl

script:
- make bootstrap all
- cp target/$TARGET/release/ts ts-$TRAVIS_TAG-$TARGET

deploy:
  provider: releases
  api_key:
    secure: nYsARwhUX2WwDtIDzm9rJ+34mA7s/1l6jpmb/5/5Qi3+bsewnmAmCeMBfa0w62ANmpg907o25xiiz7TWjcfiRllerSuppjC/jsQ8eJ5lS8Kz45AG+zHv2ElqVMq3mIsOqLFS/kMaIX2a27e285mdgaPBAgt614guagSkiGyaK0iYcWYgvb8PKrsggbwLtdJqT9qj6X5iKpje3e6aSBf7Wz0jSw1uvrn0WqLTguTvTcSaU2HdiI5jemoEMafDpo43XcAs/D/l67Wc5Hl+LbZ31wp+LKWBTQGTgNquQsK1kO3u2PSRD2buSQUkihZGS1nISUowmMn8zmt9JA29odBfZzQLh4rDgLrcTn0qVGkCQxOPYXMTgrI0dw4dTzijJ3i5B2Gs5Emkj0esgQ25+2UAQsFq+HJElxxE5SdinrfBHAy/BL39XrxdcZyC8GTvYInqaEFkoLU5y6T7ideZh4Q3Th447wjwQriCVls8aUBuASZPufItYvde/VA4pvutOGYdy6gQfRYcu9pHg1Lznf5pp5xdi0hv4hnXPQfNkQZ0Ty2n9y0oiRZXBkJirRhAvljQb70bmPN9G5BKTuSnwXH9TAevUovf1Fu0JVJcEdN+F4Ji4QZYC2t5SfKzvtI0vRYf0jnbuUQJbkoJjosCozFKpnjpE4y3hEXj/5tEFTIy2Gc=
  file: ts-$TRAVIS_TAG-$TARGET
  skip_cleanup: true
  on:
    repo: gdvalle/ts
    tags: true
